<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<AssemblyName>shadergraph</AssemblyName>
		<PackageId>shadergraph</PackageId>
		<LangVersion>14</LangVersion>
		<NoWarn>1701;1702;1591;</NoWarn>
		<WarningsAsErrors></WarningsAsErrors>
		<TreatWarningsAsErrors>True</TreatWarningsAsErrors>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<DefineConstants>SANDBOX</DefineConstants>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<OutputPath>../../../.vs/output/</OutputPath>
		<DocumentationFile>../../../.vs/output/shadergraph.xml</DocumentationFile>
		<RootNamespace>Sandbox</RootNamespace>
		<Nullable>disable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<Using Include="Sandbox.Internal.GlobalToolsNamespace" Static="true" />
		<Using Include="Sandbox.Internal.GlobalGameNamespace" Static="true" />
	</ItemGroup>

	<ItemGroup>
		<Analyzer Include="../../../bin/managed/Sandbox.CodeUpgrader.dll"/> 
		<Analyzer Include="../../../bin/managed/Sandbox.Generator.dll"/> 
		<Reference Include="../../../bin/managed/Sandbox.System.dll"/> 
		<Reference Include="../../../bin/managed/Sandbox.Engine.dll"/> 
		<Reference Include="../../../bin/managed/Sandbox.Filesystem.dll"/> 
		<Reference Include="../../../bin/managed/Sandbox.Reflection.dll"/> 
		<Reference Include="../../../bin/managed/Sandbox.Mounting.dll"/> 
		<Reference Include="../../../bin/managed/Microsoft.AspNetCore.Components.dll"/> 
		<Reference Include="../../../bin/managed/Sandbox.AppSystem.dll"/> 
		<Reference Include="../../../bin/managed/Sandbox.Tools.dll"/> 
		<Reference Include="../../../bin/managed/Sandbox.Compiling.dll"/> 
		<Reference Include="../../../bin/managed/Microsoft.CodeAnalysis.dll"/> 
		<Reference Include="../../../bin/managed/Microsoft.CodeAnalysis.CSharp.dll"/> 
		<Reference Include="../../../bin/managed/Sandbox.Bind.dll"/> 
		<Reference Include="../../../bin/managed/Facepunch.ActionGraphs.dll"/> 
		<Reference Include="../../../bin/managed/SkiaSharp.dll"/> 
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="../../../addons/tools/Code/Base Editor Library.csproj" />
	</ItemGroup>

</Project>
