<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<AssemblyName>Forkbox.Steamworks</AssemblyName>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<SatelliteResourceLanguages>en</SatelliteResourceLanguages>
		<NoWarn>1701;1702;1591</NoWarn>
		<OutputPath>../../game/bin/thirdparty</OutputPath>
		<LangVersion>14</LangVersion>
		<AllowedReferenceRelatedFileExtensions>.pdb;.xml</AllowedReferenceRelatedFileExtensions>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<TreatWarningsAsErrors>True</TreatWarningsAsErrors>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<TreatWarningsAsErrors>True</TreatWarningsAsErrors>
	</PropertyGroup>

</Project>
